package com.quasardevelopment.bodyarchitect.client.wcf.Wsdl2Code.WebServices.BasicHttpBinding_IBodyArchitectAccessService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.4
//
// Date Of Creation: 4/11/2013 5:22:00 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import com.quasardevelopment.bodyarchitect.client.wcf.WcfConstans;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.io.Serializable;
import java.util.Hashtable;
import java.util.UUID;

public class DataInfoDTO implements KvmSerializable,Serializable {
    
    public UUID activityHash;
    public UUID customerGroupHash;
    public UUID customerHash;
    public UUID exerciseHash;
    public UUID messageHash;
    public UUID myPlaceHash;
    public UUID reminderHash;
    public UUID scheduleEntryHash;
    public UUID supplementsCycleDefinitionHash;
    public UUID trainingDayHash;
    public UUID workoutPlanHash;
    
    public DataInfoDTO(){}
    
    public DataInfoDTO(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("ActivityHash"))
        {
            Object obj = soapObject.getProperty("ActivityHash");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("ActivityHash");
                activityHash = UUID.fromString(j.toString());
            }else if (obj!= null && obj instanceof String){
                activityHash = UUID.fromString((String) soapObject.getProperty("ActivityHash"));
            }
        }
        if (soapObject.hasProperty("CustomerGroupHash"))
        {
            Object obj = soapObject.getProperty("CustomerGroupHash");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("CustomerGroupHash");
                customerGroupHash = UUID.fromString(j.toString());
            }else if (obj!= null && obj instanceof String){
                customerGroupHash = UUID.fromString((String) soapObject.getProperty("CustomerGroupHash"));
            }
        }
        if (soapObject.hasProperty("CustomerHash"))
        {
            Object obj = soapObject.getProperty("CustomerHash");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("CustomerHash");
                customerHash = UUID.fromString(j.toString());
            }else if (obj!= null && obj instanceof String){
                customerHash = UUID.fromString((String) soapObject.getProperty("CustomerHash"));
            }
        }
        if (soapObject.hasProperty("ExerciseHash"))
        {
            Object obj = soapObject.getProperty("ExerciseHash");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("ExerciseHash");
                exerciseHash =UUID.fromString(j.toString());
            }else if (obj!= null && obj instanceof String){
                exerciseHash = UUID.fromString((String) soapObject.getProperty("ExerciseHash"));
            }
        }
        if (soapObject.hasProperty("MessageHash"))
        {
            Object obj = soapObject.getProperty("MessageHash");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("MessageHash");
                messageHash = UUID.fromString(j.toString());
            }else if (obj!= null && obj instanceof String){
                messageHash =UUID.fromString( (String) soapObject.getProperty("MessageHash"));
            }
        }
        if (soapObject.hasProperty("MyPlaceHash"))
        {
            Object obj = soapObject.getProperty("MyPlaceHash");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("MyPlaceHash");
                myPlaceHash = UUID.fromString(j.toString());
            }else if (obj!= null && obj instanceof String){
                myPlaceHash = UUID.fromString((String) soapObject.getProperty("MyPlaceHash"));
            }
        }
        if (soapObject.hasProperty("ReminderHash"))
        {
            Object obj = soapObject.getProperty("ReminderHash");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("ReminderHash");
                reminderHash =UUID.fromString(j.toString());
            }else if (obj!= null && obj instanceof String){
                reminderHash = UUID.fromString((String) soapObject.getProperty("ReminderHash"));
            }
        }
        if (soapObject.hasProperty("ScheduleEntryHash"))
        {
            Object obj = soapObject.getProperty("ScheduleEntryHash");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("ScheduleEntryHash");
                scheduleEntryHash =UUID.fromString(j.toString());
            }else if (obj!= null && obj instanceof String){
                scheduleEntryHash =UUID.fromString( (String) soapObject.getProperty("ScheduleEntryHash"));
            }
        }
        if (soapObject.hasProperty("SupplementsCycleDefinitionHash"))
        {
            Object obj = soapObject.getProperty("SupplementsCycleDefinitionHash");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("SupplementsCycleDefinitionHash");
                supplementsCycleDefinitionHash = UUID.fromString(j.toString());
            }else if (obj!= null && obj instanceof String){
                supplementsCycleDefinitionHash = UUID.fromString((String) soapObject.getProperty("SupplementsCycleDefinitionHash"));
            }
        }
        if (soapObject.hasProperty("TrainingDayHash"))
        {
            Object obj = soapObject.getProperty("TrainingDayHash");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("TrainingDayHash");
                trainingDayHash = UUID.fromString(j.toString());
            }else if (obj!= null && obj instanceof String){
                trainingDayHash =UUID.fromString( (String) soapObject.getProperty("TrainingDayHash"));
            }
        }
        if (soapObject.hasProperty("WorkoutPlanHash"))
        {
            Object obj = soapObject.getProperty("WorkoutPlanHash");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("WorkoutPlanHash");
                workoutPlanHash = UUID.fromString(j.toString());
            }else if (obj!= null && obj instanceof String){
                workoutPlanHash = UUID.fromString((String) soapObject.getProperty("WorkoutPlanHash"));
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return activityHash;
            case 1:
                return customerGroupHash;
            case 2:
                return customerHash;
            case 3:
                return exerciseHash;
            case 4:
                return messageHash;
            case 5:
                return myPlaceHash;
            case 6:
                return reminderHash;
            case 7:
                return scheduleEntryHash;
            case 8:
                return supplementsCycleDefinitionHash;
            case 9:
                return trainingDayHash;
            case 10:
                return workoutPlanHash;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 11;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ActivityHash";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "CustomerGroupHash";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "CustomerHash";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ExerciseHash";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "MessageHash";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "MyPlaceHash";
                break;
            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ReminderHash";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ScheduleEntryHash";
                break;
            case 8:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "SupplementsCycleDefinitionHash";
                break;
            case 9:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "TrainingDayHash";
                break;
            case 10:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "WorkoutPlanHash";
                break;
        }
        info.namespace= WcfConstans.ServiceNamespace;
    }

    

    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
