package com.quasardevelopment.bodyarchitect.client.wcf.Wsdl2Code.WebServices.BasicHttpBinding_IBodyArchitectAccessService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.4
//
// Date Of Creation: 4/11/2013 5:22:00 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import com.quasardevelopment.bodyarchitect.client.wcf.Wsdl2Code.WebServices.BasicHttpBinding_IBodyArchitectAccessService.WS_Enums.PaymentCriteria;
import com.quasardevelopment.bodyarchitect.client.wcf.Wsdl2Code.WebServices.BasicHttpBinding_IBodyArchitectAccessService.WS_Enums.ProductsSortOrder;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class GetProductsParam implements KvmSerializable {
    
    public String customerId;
    public String endTime;
    public boolean endTimeSpecified;
    public PaymentCriteria paymentCriteria;
    public boolean paymentCriteriaSpecified;
    public boolean sortAscending;
    public boolean sortAscendingSpecified;
    public ProductsSortOrder sortOrder;
    public boolean sortOrderSpecified;
    public String startTime;
    public boolean startTimeSpecified;
    
    public GetProductsParam(){}
    
    public GetProductsParam(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("CustomerId"))
        {
            Object obj = soapObject.getProperty("CustomerId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("CustomerId");
                customerId = j.toString();
            }else if (obj!= null && obj instanceof String){
                customerId = (String) soapObject.getProperty("CustomerId");
            }
        }
        if (soapObject.hasProperty("EndTime"))
        {
            Object obj = soapObject.getProperty("EndTime");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("EndTime");
                endTime = j.toString();
            }else if (obj!= null && obj instanceof String){
                endTime = (String) soapObject.getProperty("EndTime");
            }
        }
        if (soapObject.hasProperty("EndTimeSpecified"))
        {
            Object obj = soapObject.getProperty("EndTimeSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("EndTimeSpecified");
                endTimeSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                endTimeSpecified = (Boolean) soapObject.getProperty("EndTimeSpecified");
            }
        }
        if (soapObject.hasProperty("PaymentCriteria"))
        {
            Object obj = soapObject.getProperty("PaymentCriteria");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("PaymentCriteria");
                paymentCriteria = PaymentCriteria.fromString(j.toString());
            }
        }
        if (soapObject.hasProperty("PaymentCriteriaSpecified"))
        {
            Object obj = soapObject.getProperty("PaymentCriteriaSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("PaymentCriteriaSpecified");
                paymentCriteriaSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                paymentCriteriaSpecified = (Boolean) soapObject.getProperty("PaymentCriteriaSpecified");
            }
        }
        if (soapObject.hasProperty("SortAscending"))
        {
            Object obj = soapObject.getProperty("SortAscending");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("SortAscending");
                sortAscending = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                sortAscending = (Boolean) soapObject.getProperty("SortAscending");
            }
        }
        if (soapObject.hasProperty("SortAscendingSpecified"))
        {
            Object obj = soapObject.getProperty("SortAscendingSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("SortAscendingSpecified");
                sortAscendingSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                sortAscendingSpecified = (Boolean) soapObject.getProperty("SortAscendingSpecified");
            }
        }
        if (soapObject.hasProperty("SortOrder"))
        {
            Object obj = soapObject.getProperty("SortOrder");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("SortOrder");
                sortOrder = ProductsSortOrder.fromString(j.toString());
            }
        }
        if (soapObject.hasProperty("SortOrderSpecified"))
        {
            Object obj = soapObject.getProperty("SortOrderSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("SortOrderSpecified");
                sortOrderSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                sortOrderSpecified = (Boolean) soapObject.getProperty("SortOrderSpecified");
            }
        }
        if (soapObject.hasProperty("StartTime"))
        {
            Object obj = soapObject.getProperty("StartTime");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("StartTime");
                startTime = j.toString();
            }else if (obj!= null && obj instanceof String){
                startTime = (String) soapObject.getProperty("StartTime");
            }
        }
        if (soapObject.hasProperty("StartTimeSpecified"))
        {
            Object obj = soapObject.getProperty("StartTimeSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("StartTimeSpecified");
                startTimeSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                startTimeSpecified = (Boolean) soapObject.getProperty("StartTimeSpecified");
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return customerId;
            case 1:
                return endTime;
            case 2:
                return endTimeSpecified;
            case 3:
                return paymentCriteria.toString();
            case 4:
                return paymentCriteriaSpecified;
            case 5:
                return sortAscending;
            case 6:
                return sortAscendingSpecified;
            case 7:
                return sortOrder.toString();
            case 8:
                return sortOrderSpecified;
            case 9:
                return startTime;
            case 10:
                return startTimeSpecified;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 11;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "CustomerId";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "EndTime";
                break;
            case 2:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "EndTimeSpecified";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "PaymentCriteria";
                break;
            case 4:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "PaymentCriteriaSpecified";
                break;
            case 5:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "SortAscending";
                break;
            case 6:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "SortAscendingSpecified";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "SortOrder";
                break;
            case 8:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "SortOrderSpecified";
                break;
            case 9:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "StartTime";
                break;
            case 10:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "StartTimeSpecified";
                break;
        }
    }

    

    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
