package com.quasardevelopment.bodyarchitect.client.wcf.Wsdl2Code.WebServices.BasicHttpBinding_IBodyArchitectAccessService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.4
//
// Date Of Creation: 4/11/2013 5:22:00 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import com.quasardevelopment.bodyarchitect.client.wcf.Wsdl2Code.WebServices.BasicHttpBinding_IBodyArchitectAccessService.WS_Enums.CanBeIllegalCriteria;
import com.quasardevelopment.bodyarchitect.client.wcf.Wsdl2Code.WebServices.BasicHttpBinding_IBodyArchitectAccessService.WS_Enums.CriteriaOperator;
import com.quasardevelopment.bodyarchitect.client.wcf.Wsdl2Code.WebServices.BasicHttpBinding_IBodyArchitectAccessService.WS_Enums.SearchSortOrder;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class GetSupplementsCycleDefinitionsParam implements KvmSerializable {
    
    public VectorTrainingPlanDifficult difficults;
    public VectorString languages;
    public CanBeIllegalCriteria legalCriteria;
    public boolean legalCriteriaSpecified;
    public String planId;
    public VectorWorkoutPlanPurpose purposes;
    public VectorWorkoutPlanSearchCriteriaGroup searchGroups;
    public boolean sortAscending;
    public boolean sortAscendingSpecified;
    public SearchSortOrder sortOrder;
    public boolean sortOrderSpecified;
    public VectorString supplements;
    public CriteriaOperator supplementsListOperator;
    public boolean supplementsListOperatorSpecified;
    public String userId;
    
    public GetSupplementsCycleDefinitionsParam(){}
    
    public GetSupplementsCycleDefinitionsParam(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("Difficults"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("Difficults");
            difficults = new VectorTrainingPlanDifficult(j);
        }
        if (soapObject.hasProperty("Languages"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("Languages");
            languages = new VectorString(j);
        }
        if (soapObject.hasProperty("LegalCriteria"))
        {
            Object obj = soapObject.getProperty("LegalCriteria");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("LegalCriteria");
                legalCriteria = CanBeIllegalCriteria.fromString(j.toString());
            }
        }
        if (soapObject.hasProperty("LegalCriteriaSpecified"))
        {
            Object obj = soapObject.getProperty("LegalCriteriaSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("LegalCriteriaSpecified");
                legalCriteriaSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                legalCriteriaSpecified = (Boolean) soapObject.getProperty("LegalCriteriaSpecified");
            }
        }
        if (soapObject.hasProperty("PlanId"))
        {
            Object obj = soapObject.getProperty("PlanId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("PlanId");
                planId = j.toString();
            }else if (obj!= null && obj instanceof String){
                planId = (String) soapObject.getProperty("PlanId");
            }
        }
        if (soapObject.hasProperty("Purposes"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("Purposes");
            purposes = new VectorWorkoutPlanPurpose(j);
        }
        if (soapObject.hasProperty("SearchGroups"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("SearchGroups");
            searchGroups = new VectorWorkoutPlanSearchCriteriaGroup(j);
        }
        if (soapObject.hasProperty("SortAscending"))
        {
            Object obj = soapObject.getProperty("SortAscending");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("SortAscending");
                sortAscending = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                sortAscending = (Boolean) soapObject.getProperty("SortAscending");
            }
        }
        if (soapObject.hasProperty("SortAscendingSpecified"))
        {
            Object obj = soapObject.getProperty("SortAscendingSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("SortAscendingSpecified");
                sortAscendingSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                sortAscendingSpecified = (Boolean) soapObject.getProperty("SortAscendingSpecified");
            }
        }
        if (soapObject.hasProperty("SortOrder"))
        {
            Object obj = soapObject.getProperty("SortOrder");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("SortOrder");
                sortOrder = SearchSortOrder.fromString(j.toString());
            }
        }
        if (soapObject.hasProperty("SortOrderSpecified"))
        {
            Object obj = soapObject.getProperty("SortOrderSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("SortOrderSpecified");
                sortOrderSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                sortOrderSpecified = (Boolean) soapObject.getProperty("SortOrderSpecified");
            }
        }
        if (soapObject.hasProperty("Supplements"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("Supplements");
            supplements = new VectorString(j);
        }
        if (soapObject.hasProperty("SupplementsListOperator"))
        {
            Object obj = soapObject.getProperty("SupplementsListOperator");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("SupplementsListOperator");
                supplementsListOperator = CriteriaOperator.fromString(j.toString());
            }
        }
        if (soapObject.hasProperty("SupplementsListOperatorSpecified"))
        {
            Object obj = soapObject.getProperty("SupplementsListOperatorSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("SupplementsListOperatorSpecified");
                supplementsListOperatorSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                supplementsListOperatorSpecified = (Boolean) soapObject.getProperty("SupplementsListOperatorSpecified");
            }
        }
        if (soapObject.hasProperty("UserId"))
        {
            Object obj = soapObject.getProperty("UserId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("UserId");
                userId = j.toString();
            }else if (obj!= null && obj instanceof String){
                userId = (String) soapObject.getProperty("UserId");
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return difficults;
            case 1:
                return languages;
            case 2:
                return legalCriteria.toString();
            case 3:
                return legalCriteriaSpecified;
            case 4:
                return planId;
            case 5:
                return purposes;
            case 6:
                return searchGroups;
            case 7:
                return sortAscending;
            case 8:
                return sortAscendingSpecified;
            case 9:
                return sortOrder.toString();
            case 10:
                return sortOrderSpecified;
            case 11:
                return supplements;
            case 12:
                return supplementsListOperator.toString();
            case 13:
                return supplementsListOperatorSpecified;
            case 14:
                return userId;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 15;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "Difficults";
                break;
            case 1:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "Languages";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "LegalCriteria";
                break;
            case 3:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "LegalCriteriaSpecified";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "PlanId";
                break;
            case 5:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "Purposes";
                break;
            case 6:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "SearchGroups";
                break;
            case 7:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "SortAscending";
                break;
            case 8:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "SortAscendingSpecified";
                break;
            case 9:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "SortOrder";
                break;
            case 10:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "SortOrderSpecified";
                break;
            case 11:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "Supplements";
                break;
            case 12:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "SupplementsListOperator";
                break;
            case 13:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "SupplementsListOperatorSpecified";
                break;
            case 14:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "UserId";
                break;
        }
    }

    

    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
