package com.quasardevelopment.bodyarchitect.client.wcf.Wsdl2Code.WebServices.BasicHttpBinding_IBodyArchitectAccessService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.4
//
// Date Of Creation: 4/11/2013 5:22:00 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import com.quasardevelopment.bodyarchitect.client.model.PagedResultOfBase;
import com.quasardevelopment.bodyarchitect.client.wcf.ReferencesManager;
import org.ksoap2.serialization.SoapObject;

import java.util.Vector;

public class PagedResultOfSupplementCycleDefinitionDTO5oAtqRlh extends PagedResultOfBase {

    public PagedResultOfSupplementCycleDefinitionDTO5oAtqRlh() throws Exception {
        super();
    }

    public PagedResultOfSupplementCycleDefinitionDTO5oAtqRlh(SoapObject soapObject,ReferencesManager referencesTable) throws Exception
    {
        super(soapObject,referencesTable);
    }

    @Override
    protected Vector createItemVector(SoapObject soapObject, ReferencesManager referencesTable) throws Exception {
        if(soapObject==null)
        {
            return new VectorSupplementCycleDefinitionDTO();
        }
        return  new VectorSupplementCycleDefinitionDTO(soapObject,referencesTable);
    }

    
}
