package com.quasardevelopment.bodyarchitect.client.wcf.Wsdl2Code.WebServices.BasicHttpBinding_IBodyArchitectAccessService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.4
//
// Date Of Creation: 4/11/2013 5:22:00 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import com.quasardevelopment.bodyarchitect.client.util.Helper;
import com.quasardevelopment.bodyarchitect.client.wcf.ReferencesManager;
import com.quasardevelopment.bodyarchitect.client.wcf.WcfConstans;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.io.Serializable;
import java.util.Hashtable;
import java.util.UUID;

public class PictureInfoDTO implements KvmSerializable,Serializable {
    
    public String hash;
    public UUID pictureId;
    public String sessionId= Helper.emptyGuid().toString();

    public PictureInfoDTO(){}

    public PictureInfoDTO(SoapObject soapObject,ReferencesManager referencesTable)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("_x003C_Hash_x003E_k__BackingField"))
        {
            Object obj = soapObject.getProperty("_x003C_Hash_x003E_k__BackingField");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                hash = j.toString();
            }else if (obj!= null && obj instanceof String){
                hash= (String) obj;
            }
        }
        if (soapObject.hasProperty("_x003C_PictureId_x003E_k__BackingField"))
        {
            Object obj = soapObject.getProperty("_x003C_PictureId_x003E_k__BackingField");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                pictureId=UUID.fromString(j.toString());
            }else if (obj!= null && obj instanceof String){
                pictureId= UUID.fromString((String) obj);
            }
        }
        if (soapObject.hasProperty("_x003C_SessionId_x003E_k__BackingField"))
        {
            Object obj = soapObject.getProperty("_x003C_SessionId_x003E_k__BackingField");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                sessionId = j.toString();
            }else if (obj!= null && obj instanceof String){
                sessionId = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return hash;
            case 1:
                return pictureId;
            case 2:
                return sessionId;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "_x003C_Hash_x003E_k__BackingField";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "_x003C_PictureId_x003E_k__BackingField";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "_x003C_SessionId_x003E_k__BackingField";
                break;
        }
        info.namespace= WcfConstans.CollectionNamespace;
    }

    

    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
