package com.quasardevelopment.bodyarchitect.client.wcf.Wsdl2Code.WebServices.BasicHttpBinding_IBodyArchitectAccessService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.4
//
// Date Of Creation: 4/11/2013 5:22:00 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import com.quasardevelopment.bodyarchitect.client.wcf.ReferencesManager;
import com.quasardevelopment.bodyarchitect.client.wcf.Wsdl2Code.WebServices.BasicHttpBinding_IBodyArchitectAccessService.WS_Enums.PublishStatus;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.text.ParseException;
import java.util.Hashtable;

public class PlanBase implements KvmSerializable,WcfInterfaces.IReferenceObject {
    
    public String author;
    public String basedOnId;
    public String creationDate;
    public boolean creationDateSpecified;
    public String language;
    public String name;
    public UserDTO profile;
    public String publishDate;
    public boolean publishDateSpecified;
    public float rating;
    public boolean ratingSpecified;
    public PublishStatus status;
    public boolean statusSpecified;
    public float userRating;
    public boolean userRatingSpecified;
    public String userShortComment;
    public int version;
    public boolean versionSpecified;
    public String globalId;
    
    public PlanBase(){}
    
    public PlanBase(SoapObject soapObject,ReferencesManager referencesTable)         throws ParseException
    {
        if (soapObject == null)
            return;
        if (soapObject.hasAttribute("Id"))
        {
            Object obj = soapObject.getAttribute("Id");
            referencesTable.Add((String) obj, this);
        }
        if (soapObject.hasProperty("Author"))
        {
            Object obj = soapObject.getProperty("Author");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("Author");
                author = j.toString();
            }else if (obj!= null && obj instanceof String){
                author = (String) soapObject.getProperty("Author");
            }
        }
        if (soapObject.hasProperty("BasedOnId"))
        {
            Object obj = soapObject.getProperty("BasedOnId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("BasedOnId");
                basedOnId = j.toString();
            }else if (obj!= null && obj instanceof String){
                basedOnId = (String) soapObject.getProperty("BasedOnId");
            }
        }
        if (soapObject.hasProperty("CreationDate"))
        {
            Object obj = soapObject.getProperty("CreationDate");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("CreationDate");
                creationDate = j.toString();
            }else if (obj!= null && obj instanceof String){
                creationDate = (String) soapObject.getProperty("CreationDate");
            }
        }
        if (soapObject.hasProperty("CreationDateSpecified"))
        {
            Object obj = soapObject.getProperty("CreationDateSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("CreationDateSpecified");
                creationDateSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                creationDateSpecified = (Boolean) soapObject.getProperty("CreationDateSpecified");
            }
        }
        if (soapObject.hasProperty("Language"))
        {
            Object obj = soapObject.getProperty("Language");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("Language");
                language = j.toString();
            }else if (obj!= null && obj instanceof String){
                language = (String) soapObject.getProperty("Language");
            }
        }
        if (soapObject.hasProperty("Name"))
        {
            Object obj = soapObject.getProperty("Name");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("Name");
                name = j.toString();
            }else if (obj!= null && obj instanceof String){
                name = (String) soapObject.getProperty("Name");
            }
        }
        if (soapObject.hasProperty("Profile"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("Profile");
            profile = (UserDTO)referencesTable.get(j,UserDTO.class);
        }
        if (soapObject.hasProperty("PublishDate"))
        {
            Object obj = soapObject.getProperty("PublishDate");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("PublishDate");
                publishDate = j.toString();
            }else if (obj!= null && obj instanceof String){
                publishDate = (String) soapObject.getProperty("PublishDate");
            }
        }
        if (soapObject.hasProperty("PublishDateSpecified"))
        {
            Object obj = soapObject.getProperty("PublishDateSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("PublishDateSpecified");
                publishDateSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                publishDateSpecified = (Boolean) soapObject.getProperty("PublishDateSpecified");
            }
        }
        if (soapObject.hasProperty("Rating"))
        {
            Object obj = soapObject.getProperty("Rating");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("Rating");
                rating = Float.parseFloat(j.toString());
            }else if (obj!= null && obj instanceof Number){
                rating = (Integer) soapObject.getProperty("Rating");
            }
        }
        if (soapObject.hasProperty("RatingSpecified"))
        {
            Object obj = soapObject.getProperty("RatingSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("RatingSpecified");
                ratingSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                ratingSpecified = (Boolean) soapObject.getProperty("RatingSpecified");
            }
        }
        if (soapObject.hasProperty("Status"))
        {
            Object obj = soapObject.getProperty("Status");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("Status");
                status = PublishStatus.fromString(j.toString());
            }
        }
        if (soapObject.hasProperty("StatusSpecified"))
        {
            Object obj = soapObject.getProperty("StatusSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("StatusSpecified");
                statusSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                statusSpecified = (Boolean) soapObject.getProperty("StatusSpecified");
            }
        }
        if (soapObject.hasProperty("UserRating"))
        {
            Object obj = soapObject.getProperty("UserRating");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("UserRating");
                userRating = Float.parseFloat(j.toString());
            }else if (obj!= null && obj instanceof Number){
                userRating = (Integer) soapObject.getProperty("UserRating");
            }
        }
        if (soapObject.hasProperty("UserRatingSpecified"))
        {
            Object obj = soapObject.getProperty("UserRatingSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("UserRatingSpecified");
                userRatingSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                userRatingSpecified = (Boolean) soapObject.getProperty("UserRatingSpecified");
            }
        }
        if (soapObject.hasProperty("UserShortComment"))
        {
            Object obj = soapObject.getProperty("UserShortComment");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("UserShortComment");
                userShortComment = j.toString();
            }else if (obj!= null && obj instanceof String){
                userShortComment = (String) soapObject.getProperty("UserShortComment");
            }
        }
        if (soapObject.hasProperty("Version"))
        {
            Object obj = soapObject.getProperty("Version");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("Version");
                version = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                version = (Integer) soapObject.getProperty("Version");
            }
        }
        if (soapObject.hasProperty("VersionSpecified"))
        {
            Object obj = soapObject.getProperty("VersionSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("VersionSpecified");
                versionSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                versionSpecified = (Boolean) soapObject.getProperty("VersionSpecified");
            }
        }
        if (soapObject.hasProperty("GlobalId"))
        {
            Object obj = soapObject.getProperty("GlobalId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("GlobalId");
                globalId = j.toString();
            }else if (obj!= null && obj instanceof String){
                globalId = (String) soapObject.getProperty("GlobalId");
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return author;
            case 1:
                return basedOnId;
            case 2:
                return creationDate;
            case 3:
                return creationDateSpecified;
            case 4:
                return language;
            case 5:
                return name;
            case 6:
                return profile;
            case 7:
                return publishDate;
            case 8:
                return publishDateSpecified;
            case 9:
                return rating;
            case 10:
                return ratingSpecified;
            case 11:
                return status.toString();
            case 12:
                return statusSpecified;
            case 13:
                return userRating;
            case 14:
                return userRatingSpecified;
            case 15:
                return userShortComment;
            case 16:
                return version;
            case 17:
                return versionSpecified;
            case 18:
                return globalId;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 19;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Author";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "BasedOnId";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "CreationDate";
                break;
            case 3:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "CreationDateSpecified";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Language";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Name";
                break;
            case 6:
                info.type = UserDTO.class;
                info.name = "Profile";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "PublishDate";
                break;
            case 8:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "PublishDateSpecified";
                break;
            case 9:
                info.type = Float.class;
                info.name = "Rating";
                break;
            case 10:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "RatingSpecified";
                break;
            case 11:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Status";
                break;
            case 12:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "StatusSpecified";
                break;
            case 13:
                info.type = Float.class;
                info.name = "UserRating";
                break;
            case 14:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "UserRatingSpecified";
                break;
            case 15:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "UserShortComment";
                break;
            case 16:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "Version";
                break;
            case 17:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "VersionSpecified";
                break;
            case 18:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "GlobalId";
                break;
        }
    }

    

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
