package com.quasardevelopment.bodyarchitect.client.wcf.Wsdl2Code.WebServices.BasicHttpBinding_IBodyArchitectAccessService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.4
//
// Date Of Creation: 4/11/2013 5:22:00 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import com.quasardevelopment.bodyarchitect.client.wcf.ReferencesManager;
import com.quasardevelopment.bodyarchitect.client.wcf.WcfConstans;
import com.quasardevelopment.bodyarchitect.client.wcf.Wsdl2Code.WebServices.BasicHttpBinding_IBodyArchitectAccessService.WS_Enums.LengthType;
import com.quasardevelopment.bodyarchitect.client.wcf.Wsdl2Code.WebServices.BasicHttpBinding_IBodyArchitectAccessService.WS_Enums.ProfileNotification;
import com.quasardevelopment.bodyarchitect.client.wcf.Wsdl2Code.WebServices.BasicHttpBinding_IBodyArchitectAccessService.WS_Enums.WeightType;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.io.Serializable;
import java.util.EnumSet;
import java.util.Hashtable;
import java.util.UUID;

public class ProfileSettingsDTO extends BAGlobalObject implements KvmSerializable,Serializable,WcfInterfaces.IReferenceObject {
    
    public boolean allowTrainingDayComments;
    public boolean automaticUpdateMeasurements;
    public LengthType lengthType;
    public EnumSet<ProfileNotification> notificationBlogCommentAdded;
    public EnumSet<ProfileNotification> notificationFollowersChangedCalendar;
    public EnumSet<ProfileNotification> notificationFriendChangedCalendar;
    public EnumSet<ProfileNotification> notificationSocial;
    public EnumSet<ProfileNotification> notificationVoted;
    public WeightType weightType;
    
    public ProfileSettingsDTO(){}
    
    public ProfileSettingsDTO(SoapObject soapObject,ReferencesManager referencesTable)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasAttribute("Id"))
        {
            Object obj = soapObject.getAttribute("Id");
            referencesTable.Add((String) obj, this);
        }
        if (soapObject.hasProperty("AllowTrainingDayComments"))
        {
            Object obj = soapObject.getProperty("AllowTrainingDayComments");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("AllowTrainingDayComments");
                allowTrainingDayComments = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                allowTrainingDayComments = (Boolean) soapObject.getProperty("AllowTrainingDayComments");
            }
        }
        if (soapObject.hasProperty("AutomaticUpdateMeasurements"))
        {
            Object obj = soapObject.getProperty("AutomaticUpdateMeasurements");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("AutomaticUpdateMeasurements");
                automaticUpdateMeasurements = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                automaticUpdateMeasurements = (Boolean) soapObject.getProperty("AutomaticUpdateMeasurements");
            }
        }
        if (soapObject.hasProperty("LengthType"))
        {
            Object obj = soapObject.getProperty("LengthType");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("LengthType");
                lengthType = LengthType.fromString(j.toString());
            }
        }
        if (soapObject.hasProperty("NotificationBlogCommentAdded"))
        {
            Object obj = soapObject.getProperty("NotificationBlogCommentAdded");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("NotificationBlogCommentAdded");
                notificationBlogCommentAdded = ProfileNotification.getStatusFlags(j.toString());
            }
        }
        if (soapObject.hasProperty("NotificationFollowersChangedCalendar"))
        {
            Object obj = soapObject.getProperty("NotificationFollowersChangedCalendar");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("NotificationFollowersChangedCalendar");
                notificationFollowersChangedCalendar = ProfileNotification.getStatusFlags(j.toString());
            }
        }
        if (soapObject.hasProperty("NotificationFriendChangedCalendar"))
        {
            Object obj = soapObject.getProperty("NotificationFriendChangedCalendar");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("NotificationFriendChangedCalendar");
                notificationFriendChangedCalendar = ProfileNotification.getStatusFlags(j.toString());
            }
        }
        if (soapObject.hasProperty("NotificationSocial"))
        {
            Object obj = soapObject.getProperty("NotificationSocial");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("NotificationSocial");
                notificationSocial = ProfileNotification.getStatusFlags(j.toString());
            }
        }
        if (soapObject.hasProperty("NotificationVoted"))
        {
            Object obj = soapObject.getProperty("NotificationVoted");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("NotificationVoted");
                notificationVoted = ProfileNotification.getStatusFlags(j.toString());
            }
        }
        if (soapObject.hasProperty("WeightType"))
        {
            Object obj = soapObject.getProperty("WeightType");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("WeightType");
                weightType = WeightType.fromString(j.toString());
            }
        }
        if (soapObject.hasProperty("GlobalId"))
        {
            Object obj = soapObject.getProperty("GlobalId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("GlobalId");
                globalId = UUID.fromString(j.toString());
            }else if (obj!= null && obj instanceof String){
                globalId = UUID.fromString((String) soapObject.getProperty("GlobalId"));
            }
        }
    }



    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return globalId;
            case 1:
                return allowTrainingDayComments;
            case 2:
                return automaticUpdateMeasurements;
            case 3:
                return lengthType.toString();
            case 4:
                return ProfileNotification.getProfileNotificationValue(notificationBlogCommentAdded);
            case 5:
                return ProfileNotification.getProfileNotificationValue(notificationFollowersChangedCalendar);
            case 6:
                return ProfileNotification.getProfileNotificationValue(notificationFriendChangedCalendar);
            case 7:
                return ProfileNotification.getProfileNotificationValue(notificationSocial);
            case 8:
                return ProfileNotification.getProfileNotificationValue(notificationVoted);
            case 9:
                return weightType.toString();

        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 10;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "GlobalId";
                break;
            case 1:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "AllowTrainingDayComments";
                break;
            case 2:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "AutomaticUpdateMeasurements";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "LengthType";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "NotificationBlogCommentAdded";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "NotificationFollowersChangedCalendar";
                break;
            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "NotificationFriendChangedCalendar";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "NotificationSocial";
                break;
            case 8:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "NotificationVoted";
                break;
            case 9:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "WeightType";
                break;

        }
        info.namespace= WcfConstans.ServiceNamespace;
    }

    

    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
