package com.quasardevelopment.bodyarchitect.client.wcf.Wsdl2Code.WebServices.BasicHttpBinding_IBodyArchitectAccessService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.4
//
// Date Of Creation: 4/11/2013 5:22:00 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import com.quasardevelopment.bodyarchitect.client.wcf.ReferencesManager;
import com.quasardevelopment.bodyarchitect.client.wcf.WcfConstans;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;

import java.text.ParseException;
import java.util.Hashtable;

public class ProfileUpdateData implements KvmSerializable {
    
    public ProfileDTO profile;
    public WymiaryDTO wymiary;
    
    public ProfileUpdateData(){}
    
    public ProfileUpdateData(SoapObject soapObject,ReferencesManager referencesTable)       throws ParseException
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("Profile"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("Profile");
            profile =  new ProfileDTO (j,referencesTable);
            
        }
        if (soapObject.hasProperty("Wymiary"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("Wymiary");
            wymiary = (WymiaryDTO)referencesTable.get(j,WymiaryDTO.class);
            
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return profile;
            case 1:
                return wymiary;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 2;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = ProfileDTO.class;
                info.name = "Profile";
                break;
            case 1:
                info.type = WymiaryDTO.class;
                info.name = "Wymiary";
                break;
        }
        info.namespace= WcfConstans.ServiceNamespace;
    }

    

    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
