package com.quasardevelopment.bodyarchitect.client.wcf.Wsdl2Code.WebServices.BasicHttpBinding_IBodyArchitectAccessService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.4
//
// Date Of Creation: 4/11/2013 5:22:00 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import com.quasardevelopment.bodyarchitect.client.wcf.ReferencesManager;
import com.quasardevelopment.bodyarchitect.client.wcf.Wsdl2Code.WebServices.BasicHttpBinding_IBodyArchitectAccessService.WS_Enums.TrainingDayOperationType;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.text.ParseException;
import java.util.Hashtable;

public class TrainingDayCommentOperationParam implements KvmSerializable {
    
    public TrainingDayCommentDTO comment;
    public TrainingDayOperationType operationType;
    public boolean operationTypeSpecified;
    public String trainingDayId;
    
    public TrainingDayCommentOperationParam(){}
    
    public TrainingDayCommentOperationParam(SoapObject soapObject,ReferencesManager referencesTable)    throws ParseException
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("Comment"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("Comment");
            comment =  new TrainingDayCommentDTO (j,referencesTable);
            
        }
        if (soapObject.hasProperty("OperationType"))
        {
            Object obj = soapObject.getProperty("OperationType");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("OperationType");
                operationType = TrainingDayOperationType.fromString(j.toString());
            }
        }
        if (soapObject.hasProperty("OperationTypeSpecified"))
        {
            Object obj = soapObject.getProperty("OperationTypeSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("OperationTypeSpecified");
                operationTypeSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                operationTypeSpecified = (Boolean) soapObject.getProperty("OperationTypeSpecified");
            }
        }
        if (soapObject.hasProperty("TrainingDayId"))
        {
            Object obj = soapObject.getProperty("TrainingDayId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) soapObject.getProperty("TrainingDayId");
                trainingDayId = j.toString();
            }else if (obj!= null && obj instanceof String){
                trainingDayId = (String) soapObject.getProperty("TrainingDayId");
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return comment;
            case 1:
                return operationType.toString();
            case 2:
                return operationTypeSpecified;
            case 3:
                return trainingDayId;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 4;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = TrainingDayCommentDTO.class;
                info.name = "Comment";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "OperationType";
                break;
            case 2:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "OperationTypeSpecified";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "TrainingDayId";
                break;
        }
    }

    

    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
